# Blog settings
# permalink: /blog/:title


# My variables
name: Nikhil. R
description: Raw Thoughts
google_verification: null
email: rnikhil96@outlook.com
author: Nikhil. R


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass
gems:
  - jekyll-sitemap


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
