  # Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nikhil. R
tagline:          ''
description:      'test'
url:              http://rnikhil275.github.io

author:
  name:           'Nikhil. R'
  url:            https://twitter.com/rnikhil275

paginate:         5

# Custom vars
version:          1.0.0


github:
  repo:           https://github.com/rnikhil275/rnikhil275.github.io
